# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -o goum_server-x64 server/server.go 
    - name: Upload compiled binary
      uses: actions/upload-artifact@v4
      with:
        name: goum_server-x64
        path: ./goum_server-x64

    - name: Build client x64
      working-directory: ./client
      run: go build -o ../goum_client-x64
    - name: Upload compiled binary
      uses: actions/upload-artifact@v4
      with:
        name: goum_client-x64
        path: ./goum_client-x64

    - name: Build client mips
      working-directory: ./client
      run: GOARCH=mips GOOS=linux go build -o ../goum_client-mips
    - name: Upload compiled binary
      uses: actions/upload-artifact@v4
      with:
        name: goum_client-mips
        path: ./goum_client-mips

    - name: Build client mipsle
      working-directory: ./client
      run: GOARCH=mipsle GOOS=linux go build -o ../goum_client-mipsle 
    - name: Upload compiled binary
      uses: actions/upload-artifact@v4
      with:
        name: goum_client-mipsle
        path: ./goum_client-mipsle

    - name: Build client arm64
      working-directory: ./client
      run: GOARCH=arm64 GOOS=linux go build -o ../goum_client-arm64 
    - name: Upload compiled binary
      uses: actions/upload-artifact@v4
      with:
        name: goum_client-arm64
        path: ./goum_client-arm64

    - name: Build client arm
      working-directory: ./client
      run: GOARCH=arm GOOS=linux go build -o ../goum_client-arm 
    - name: Upload compiled binary
      uses: actions/upload-artifact@v4
      with:
        name: goum_client-arm
        path: ./goum_client-arm

    - name: Build client i386
      working-directory: ./client
      run: GOARCH=386 GOOS=linux go build -o ../goum_client-i386
    - name: Upload compiled binary
      uses: actions/upload-artifact@v4
      with:
        name: goum_client-i386
        path: ./goum_client-i386

    - name: Build client ppc64le
      working-directory: ./client
      run: GOARCH=ppc64le GOOS=linux go build -o ../goum_client-ppc64le 
    - name: Upload compiled binary
      uses: actions/upload-artifact@v4
      with:
        name: goum_client-ppc64le
        path: ./goum_client-ppc64le

    - name: Build client ppc64
      working-directory: ./client
      run: GOARCH=ppc64 GOOS=linux go build -o ../goum_client-ppc64 
    - name: Upload compiled binary
      uses: actions/upload-artifact@v4
      with:
        name: goum_client-ppc64
        path: ./goum_client-ppc64

    - name: Build client mips64le
      working-directory: ./client
      run: GOARCH=mips64le GOOS=linux go build -o ../goum_client-mips64le 
    - name: Upload compiled binary
      uses: actions/upload-artifact@v4
      with:
        name: goum_client-mips64le
        path: ./goum_client-mips64le

    - name: Build client mips64
      working-directory: ./client
      run: GOARCH=mips64 GOOS=linux go build -o ../goum_client-mips64 
    - name: Upload compiled binary
      uses: actions/upload-artifact@v4
      with:
        name: goum_client-mips64
        path: ./goum_client-mips64
